<?php
require_once __DIR__.'/../dbConnection.php';

// Check for Dompdf (Composer or manual)
$autoload1 = __DIR__.'/../vendor/autoload.php';
$autoload2 = __DIR__.'/../dompdf/autoload.inc.php';
if (file_exists($autoload1)) {
    require_once $autoload1;
} elseif (file_exists($autoload2)) {
    require_once $autoload2;
} else {
    die('❌ Dompdf not found. Please install using composer or place dompdf folder.');
}

use Dompdf\Dompdf;
use Dompdf\Options;

// Prepare data
$sql = "SELECT e.exam_title, s.subject_name,
        COUNT(ea.attempt_id) AS total,
        ROUND(AVG(ea.score),1) AS avg
        FROM exam_attempts ea
        JOIN exams e ON ea.exam_id=e.exam_id
        JOIN subjects s ON e.subject_id=s.subject_id
        WHERE ea.submitted=1
        GROUP BY e.exam_id";
$rows = $pdo->query($sql)->fetchAll();

// Prepare HTML content
$logoPath = __DIR__ . '/../assets/images/logo.jpeg'; // <-- put your logo here
$logoBase64 = '';
if (file_exists($logoPath)) {
    $logoData = file_get_contents($logoPath);
    $logoBase64 = 'data:image/png;base64,' . base64_encode($logoData);
}

$html = '
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
body {
    font-family: "Poppins", sans-serif;
    margin: 0;
    padding: 0;
    color: #333;
    background: #fff;
}
.header {
    display: flex;
    align-items: center;
    border-bottom: 3px solid #007bff;
    padding: 10px 0 5px;
}
.header img {
    height: 50px;
    margin-right: 10px;
}
.header .title {
    font-size: 20px;
    font-weight: 700;
    color: #007bff;
}
.report-title {
    text-align: center;
    margin-top: 15px;
    font-size: 18px;
    font-weight: 600;
    color: #222;
    text-transform: uppercase;
}
table {
    border-collapse: collapse;
    width: 100%;
    margin-top: 15px;
    font-size: 12px;
}
th, td {
    border: 1px solid #ccc;
    padding: 8px 10px;
    text-align: center;
}
th {
    background: #007bff;
    color: #fff;
    text-transform: uppercase;
    font-size: 13px;
}
tr:nth-child(even) {
    background: #f9f9f9;
}
.footer {
    margin-top: 30px;
    text-align: right;
    font-size: 11px;
    color: #555;
    border-top: 2px solid #007bff;
    padding-top: 5px;
}
</style>
</head>
<body>
<div class="header">
';

// Logo if available
if ($logoBase64 !== '') {
    $html .= '<img src="'.$logoBase64.'" alt="Logo">';
}
$html .= '<div class="title">Agumentik Software Pvt. Ltd.</div>
</div>
<div class="report-title">Exam Performance Report</div>
<table>
<thead>
<tr>
  <th>Exam</th>
  <th>Subject</th>
  <th>Students Appeared</th>
  <th>Average Score</th>
</tr>
</thead>
<tbody>';

if (empty($rows)) {
    $html .= '<tr><td colspan="4">No data available</td></tr>';
} else {
    foreach ($rows as $r) {
        $html .= '<tr>
            <td>'.htmlspecialchars($r['exam_title']).'</td>
            <td>'.htmlspecialchars($r['subject_name']).'</td>
            <td>'.$r['total'].'</td>
            <td>'.$r['avg'].'</td>
        </tr>';
    }
}

$html .= '</tbody>
</table>
<div class="footer">
Generated by <b>Agumentik System</b> | '.date("d M Y, h:i A").'
</div>
</body>
</html>';

// Setup Dompdf options
$options = new Options();
$options->set('isRemoteEnabled', true);
$options->set('isHtml5ParserEnabled', true);

$dompdf = new Dompdf($options);
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();

// Output file
$dompdf->stream('exam_report.pdf', ['Attachment' => true]);
exit;
